big_data: big_data.c
	gcc -o big_data big_data.c

socket: socket.c
	gcc -o socket socket.c

read_secret: read_secret.c
	gcc -o read_secret read_secret.c

pong: pong.c
	gcc -o pong pong.c

mem_char: mem_char.c
	gcc -o mem_char mem_char.c

sigbus_save: sigbus_save.c
	gcc -o sigbus_save sigbus_save.c

set_pid: set_pid.c
	gcc -o set_pid set_pid.c

